version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_erp
    environment:
      MYSQL_ROOT_PASSWORD: 89631139
      MYSQL_DATABASE: erpdb
      MYSQL_USER: hygino
      MYSQL_PASSWORD: 89631139
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: